### ISSUE TITLE
Popup page with 7 icons of the top features.

### ISSUE THREAD

**Issue by Haywhyoh** [Haywhyoh/Browser_assistant#1]
- Organize idea icon
- Watch the Youtube videos icon
- Summarise with ChatGpt icon
- Ask ChatGpt icon
- Play games icon
- Take screenshots icon

Clicking these icons should give users access to the following features.

**Comment by Dolamu-TheDataGuy** [comment]
What language are we going to be using preferably?

**Comment by Haywhyoh** [comment]
Javascript

**Comment by Haywhyoh** [comment]
> What language are we going to be using preferably?

JavaScript
